// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateTodoRes interface {
	createTodoRes()
}

type DeleteTodoRes interface {
	deleteTodoRes()
}

type ListTodoRes interface {
	listTodoRes()
}

type ReadTodoRes interface {
	readTodoRes()
}

type UpdateTodoRes interface {
	updateTodoRes()
}
