// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"math"
	"net"
	"net/http"
	"net/url"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/json"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

// No-op definition for keeping imports.
var (
	_ = context.Background()
	_ = fmt.Stringer(nil)
	_ = strings.Builder{}
	_ = errors.Is
	_ = sort.Ints
	_ = http.MethodGet
	_ = io.Copy
	_ = json.Marshal
	_ = bytes.NewReader
	_ = strconv.ParseInt
	_ = time.Time{}
	_ = conv.ToInt32
	_ = uuid.UUID{}
	_ = uri.PathEncoder{}
	_ = url.URL{}
	_ = math.Mod
	_ = validate.Int{}
	_ = ht.NewRequest
	_ = net.IP{}
	_ = otelogen.Version
	_ = trace.TraceIDFromHex
	_ = otel.GetTracerProvider
	_ = metric.NewNoopMeterProvider
	_ = regexp.MustCompile
	_ = jx.Null
	_ = sync.Pool{}
)

func (s *Server) notFound(w http.ResponseWriter, r *http.Request) {
	http.NotFound(w, r)
}

func skipSlash(p string) string {
	if len(p) > 0 && p[0] == '/' {
		return p[1:]
	}
	return p
}

// nextElem return next path element from p and forwarded p.
func nextElem(p string) (elem, next string) {
	p = skipSlash(p)
	idx := strings.IndexByte(p, '/')
	if idx < 0 {
		idx = len(p)
	}
	return p[:idx], p[idx:]
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	p := r.URL.Path
	if len(p) == 0 {
		s.notFound(w, r)
		return
	}

	var (
		elem string            // current element, without slashes
		args map[string]string // lazily initialized
	)

	// Static code generated router with unwrapped path search.
	switch r.Method {
	case "DELETE":
		// Root edge.
		elem, p = nextElem(p)
		switch elem {
		case "categories": // -> 1
			// Edge: 1, path: "categories".
			elem, p = nextElem(p)
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// DELETE /categories/{id}
				s.handleDeleteCategoryRequest(args, w, r)
				return
			}
		case "pets": // -> 3
			// Edge: 3, path: "pets".
			elem, p = nextElem(p)
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// Edge: 4, path: "".
				elem, p = nextElem(p)
				if len(elem) == 0 {
					// DELETE /pets/{id}.
					s.handleDeletePetRequest(args, w, r)
					return
				}
				switch elem {
				case "owner": // -> 5
					// DELETE /pets/{id}/owner
					s.handleDeletePetOwnerRequest(args, w, r)
					return
				default:
					// DELETE /pets/{id}.
					s.handleDeletePetRequest(args, w, r)
					return
				}
			}
		case "users": // -> 6
			// Edge: 6, path: "users".
			elem, p = nextElem(p)
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// DELETE /users/{id}
				s.handleDeleteUserRequest(args, w, r)
				return
			}
		default:
			s.notFound(w, r)
			return
		}
	case "GET":
		// Root edge.
		elem, p = nextElem(p)
		switch elem {
		case "categories": // -> 1
			// Edge: 1, path: "categories".
			elem, p = nextElem(p)
			if len(elem) == 0 {
				// GET /categories.
				s.handleListCategoryRequest(args, w, r)
				return
			}
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// Edge: 2, path: "".
				elem, p = nextElem(p)
				if len(elem) == 0 {
					// GET /categories/{id}.
					s.handleReadCategoryRequest(args, w, r)
					return
				}
				switch elem {
				case "pets": // -> 3
					// GET /categories/{id}/pets
					s.handleListCategoryPetsRequest(args, w, r)
					return
				default:
					// GET /categories/{id}.
					s.handleReadCategoryRequest(args, w, r)
					return
				}
			}
		case "pets": // -> 4
			// Edge: 4, path: "pets".
			elem, p = nextElem(p)
			if len(elem) == 0 {
				// GET /pets.
				s.handleListPetRequest(args, w, r)
				return
			}
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// Edge: 5, path: "".
				elem, p = nextElem(p)
				if len(elem) == 0 {
					// GET /pets/{id}.
					s.handleReadPetRequest(args, w, r)
					return
				}
				switch elem {
				case "categories": // -> 6
					// GET /pets/{id}/categories
					s.handleListPetCategoriesRequest(args, w, r)
					return
				case "friends": // -> 7
					// GET /pets/{id}/friends
					s.handleListPetFriendsRequest(args, w, r)
					return
				case "owner": // -> 11
					// GET /pets/{id}/owner
					s.handleReadPetOwnerRequest(args, w, r)
					return
				default:
					// GET /pets/{id}.
					s.handleReadPetRequest(args, w, r)
					return
				}
			}
		case "users": // -> 8
			// Edge: 8, path: "users".
			elem, p = nextElem(p)
			if len(elem) == 0 {
				// GET /users.
				s.handleListUserRequest(args, w, r)
				return
			}
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// Edge: 9, path: "".
				elem, p = nextElem(p)
				if len(elem) == 0 {
					// GET /users/{id}.
					s.handleReadUserRequest(args, w, r)
					return
				}
				switch elem {
				case "pets": // -> 10
					// GET /users/{id}/pets
					s.handleListUserPetsRequest(args, w, r)
					return
				default:
					// GET /users/{id}.
					s.handleReadUserRequest(args, w, r)
					return
				}
			}
		default:
			s.notFound(w, r)
			return
		}
	case "PATCH":
		// Root edge.
		elem, p = nextElem(p)
		switch elem {
		case "categories": // -> 1
			// Edge: 1, path: "categories".
			elem, p = nextElem(p)
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// PATCH /categories/{id}
				s.handleUpdateCategoryRequest(args, w, r)
				return
			}
		case "pets": // -> 3
			// Edge: 3, path: "pets".
			elem, p = nextElem(p)
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// PATCH /pets/{id}
				s.handleUpdatePetRequest(args, w, r)
				return
			}
		case "users": // -> 5
			// Edge: 5, path: "users".
			elem, p = nextElem(p)
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// PATCH /users/{id}
				s.handleUpdateUserRequest(args, w, r)
				return
			}
		default:
			s.notFound(w, r)
			return
		}
	case "POST":
		// Root edge.
		elem, p = nextElem(p)
		switch elem {
		case "categories": // -> 1
			// Edge: 1, path: "categories".
			elem, p = nextElem(p)
			if len(elem) == 0 {
				// POST /categories.
				s.handleCreateCategoryRequest(args, w, r)
				return
			}
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// Edge: 2, path: "".
				elem, p = nextElem(p)
				switch elem {
				case "pets": // -> 3
					// POST /categories/{id}/pets
					s.handleCreateCategoryPetsRequest(args, w, r)
					return
				default:
					s.notFound(w, r)
					return
				}
			}
		case "pets": // -> 4
			// Edge: 4, path: "pets".
			elem, p = nextElem(p)
			if len(elem) == 0 {
				// POST /pets.
				s.handleCreatePetRequest(args, w, r)
				return
			}
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// Edge: 5, path: "".
				elem, p = nextElem(p)
				switch elem {
				case "categories": // -> 6
					// POST /pets/{id}/categories
					s.handleCreatePetCategoriesRequest(args, w, r)
					return
				case "friends": // -> 7
					// POST /pets/{id}/friends
					s.handleCreatePetFriendsRequest(args, w, r)
					return
				case "owner": // -> 8
					// POST /pets/{id}/owner
					s.handleCreatePetOwnerRequest(args, w, r)
					return
				default:
					s.notFound(w, r)
					return
				}
			}
		case "users": // -> 9
			// Edge: 9, path: "users".
			elem, p = nextElem(p)
			if len(elem) == 0 {
				// POST /users.
				s.handleCreateUserRequest(args, w, r)
				return
			}
			switch elem {
			default:
				if args == nil {
					args = make(map[string]string)
				}
				args["id"] = elem
				// Edge: 10, path: "".
				elem, p = nextElem(p)
				switch elem {
				case "pets": // -> 11
					// POST /users/{id}/pets
					s.handleCreateUserPetsRequest(args, w, r)
					return
				default:
					s.notFound(w, r)
					return
				}
			}
		default:
			s.notFound(w, r)
			return
		}
	default:
		s.notFound(w, r)
		return
	}
}
