// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateCategoryRes interface {
	createCategoryRes()
}

type CreatePetRes interface {
	createPetRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteCategoryRes interface {
	deleteCategoryRes()
}

type DeletePetRes interface {
	deletePetRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListCategoryPetsRes interface {
	listCategoryPetsRes()
}

type ListCategoryRes interface {
	listCategoryRes()
}

type ListPetCategoriesRes interface {
	listPetCategoriesRes()
}

type ListPetFriendsRes interface {
	listPetFriendsRes()
}

type ListPetRes interface {
	listPetRes()
}

type ListUserPetsRes interface {
	listUserPetsRes()
}

type ListUserRes interface {
	listUserRes()
}

type ReadCategoryRes interface {
	readCategoryRes()
}

type ReadPetOwnerRes interface {
	readPetOwnerRes()
}

type ReadPetRes interface {
	readPetRes()
}

type ReadUserBestFriendRes interface {
	readUserBestFriendRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateCategoryRes interface {
	updateCategoryRes()
}

type UpdatePetRes interface {
	updatePetRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
